A fix for annoying clang error "unused-const-variabl" in third_party code.
../../third_party/externals/libwebp/src/enc/quant.c:105:23: error: unused variable 'kCoeffThresh' [-Werror,-Wunused-const-variable]
static const uint16_t kCoeffThresh[16] = {
                              ^
                      1 error generated.

BUG=None
TEST=build with clang, ninja -C out/Debug most.
R=bsalomon@google.com, epoger@google.com, thakis@chromium.org, mtklein@google.com

Author: tfarina@chromium.org

Review URL: https://codereview.chromium.org/47603012

git-svn-id: http://skia.googlecode.com/svn/trunk/gyp@11990 2bbb7eff-a529-9590-31e7-b0007b416f81